### ISSUE TITLE
Chromatics 2.0 doesn't work on my blackwidow chroma

### ISSUE THREAD

**Issue by neveah25** [roxaskeyheart/Chromatics#24] opened 2017-03-07 20:52 UTC
Hi, first of all, forgive me for my bad english as it's not my main language. 

So tonight i decided to give a try to your software. It actually looks amazing but i'm having issues with it.
I deleted the ACT plugging, Visual studio and .Net Framework are updated; Razer Synapse aswell and Chromatics is allowed. But once i start the game, the keyboard colour stays blue (I guess the main one ?) and nothing else changes. I was wondering if I did a wrong manipulation or something else. 
![17193728_1756086158037378_542092946_o](https://cloud.githubusercontent.com/assets/26260589/23677368/1c61e1de-0380-11e7-9e4c-bfb1e61b972e.jpg) 

As u can see. It just stays this way and never does anything else. 

I hope you know a way to resolve this problem because I really want to give a try at your software. You really put an amazing job into it ! 

Have a great day, cordialy Neveah

**Comment by logicallysynced** [comment] 2017-03-07 22:58
Are you playing the DX9 version of the game? Chromatics only supports DX9 currently. Also have you set the app to run as an admin?

If you are, can you copy paste the console/debug tab in the Chromatics here?

**Comment by untruereality** [comment] 2017-03-08 00:37
Hey,
I have exactly the same issue as well, at first I did still have DX11 and the change log got the point of saying I was at the main menu and nothing else. I then changed to DX9 (The setting in the launcher config) and now the Chromatics change log won't detect that game has launched. 

Hello World
Searching for devices.chromatics..
Attempting to load devices.chromatics..
devices.chromatics loaded.
Searching for settings.chromatics..
Attempting to load settings.chromatics..
settings.chromatics loaded.
Searching for mappings.chromatics..
Attempting to load mappings.chromatics..
mappings.chromatics loaded.
Architecture: x64
Razer SDK Detected: C:\Program Files\Razer Chroma SDK\bin\RzChromaSDK64.dll
Start Colore Setup
Colore Already loaded.
Razer SDK Loaded
Attempting to load CUE SDK..
CUE SDK failed to load. EX: Error in the application.
Attempting to load Logitech SDK..
Logitech SDK failed to load.
Attempting to load LIFX SDK..
LIFX SDK Loaded
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..

Those last lines continue even after the game has launched, so my Blackwidow chroma and Mamba TE both remain that light blue colour. I have also made sure that everything has been updated the same as Neveah, and made sure it was run as Admin. 
Hope we can resolve this issue. 
Cheers

**Comment by logicallysynced** [comment] 2017-03-08 01:01
So just a couple of basic things to check before going deeper:

1. Are you running chromatics.exe as administrator? (Right-click exe, properties, compatibility, run as administrator).
2. Have you tried closing out of both FFXIV and Chromatics after switching to DX9 mode and restarting both programs, first Chromatics and then FFXIV? (Or reboot the computer to make sure)
3. Are you using the installer or portable version?

**Comment by untruereality** [comment] 2017-03-08 11:09
Yeah Chromatics is being run as administrator, I tried closing both programmes yesterday and seeing if it would load, multiple times. Then today I have just turned my PC on again to check and it does exactly the same thing. I am using the Installer.

**Comment by logicallysynced** [comment] 2017-03-08 17:36
I'm having some trouble reproducing this issue since it seems to work fine for me on all my computers.

I'm unsure if it could be some antivirus or similar preventing Chromatics from attaching to FFXIV.

I'll keep investigating but just letting you know it may take longer than I originally expected :/

**Comment by neveah25** [comment] 2017-03-09 17:11
My apologies for the late reply, had a busy day yesterday. So  I didn't realise it had to be launch with dx9 but even with that change it still doesn't work.

**Comment by roxaskeyheart** [comment] 2017-03-10 03:15
What game language do you have FFXIV set to may I ask?

**Comment by logicallysynced** [comment] 2017-03-10 04:27
Okay I have released an update for Chromatics (2.0.2) so you should get prompted to update the next time you open Chromatics. I am unsure if this will fix your issue or not (as I currently can't reproduce the error) however I have made some slight tweaks that might help.

At the very least I have also added some more debugging information to the console, so if it's still not working please copy and paste the entire console and post it here for me.

**Comment by untruereality** [comment] 2017-03-10 19:52
I've got the update and it hasn't fixed the issue but it seems to be an attaching issue. This is what the debug tab shows: 

Starting Chromatics Version 2.0.2 (Beta)
Searching for devices.chromatics..
Attempting to load devices.chromatics..
devices.chromatics loaded.
Searching for settings.chromatics..
Attempting to load settings.chromatics..
settings.chromatics loaded.
Searching for mappings.chromatics..
Attempting to load mappings.chromatics..
mappings.chromatics loaded.
Architecture: x64
Razer SDK Detected: C:\Program Files\Razer Chroma SDK\bin\RzChromaSDK64.dll
Start Colore Setup
Colore Already loaded.
Razer SDK Loaded
Attempting to load CUE SDK..
CUE SDK failed to load. EX: Error in the application.
Attempting to load Logitech SDK..
Logitech SDK failed to load.
Attempting to load LIFX SDK..
LIFX SDK Loaded
Waiting for Game Launch..
Waiting for Game Launch..

-[Keeps repeating until I launch XIV and then]-
 
Attempting Attach..

Hope this helps, I don't know if it would make a difference but I am running FFXIV and Chromatics on a HDD and my OS is on a separate SSD. Don't know if that would make a difference.

Cheers.

**Comment by logicallysynced** [comment] 2017-03-10 21:21
For the sake of further testing, could you try downloading and running the portable version of the app to see if that works any better? Make sure to read the instructions on https://chromaticsffxiv.com/download.html as there are a few extra steps.

If this still doesn't work, there are a few .json files in the portable directory that get generated after the first run, could you upload them here for me?

**Comment by untruereality** [comment] 2017-03-11 13:49
Using the portable version fixes it, it works now. So thanks for that and sorry for not trying it sooner. 
Thank you very much.

**Comment by logicallysynced** [comment] 2017-03-11 14:57
No worries, it's possible if you copy and replace the four .json files from the portable version to your installer version files (in Program Files) that might also resolve it.

For the sake of future debugging if you could check for me I would be very grateful. :)

Glad you got it working though.

**Comment by neveah25** [comment] 2017-03-11 16:13
So. thez 2.0.2 from installer still doesn't work. I've tried the portable one. And... It only launches if i disable Avast and it still doesn't work. But the software made it further. It attached to ffxiv and then said "connected to the game (character name) but still nothing on the keyboard. It ended up writing "failure of the sequence".
I can copy past you the consol if you want but it's in french so i don't know if it's gonna help you or not.

To resume. What i've noticed is the portable sotfware worked better than the installler even though it's blocked by Avast (went further. Had a message saying that Chromatics.exe was attached to ffxiv with the window sounds. Message that I haven't had before.)

**Comment by neveah25** [comment] 2017-03-11 16:20
And I've noticed something else. Pretty hard to explain but i'm gonna give it a try. I closed FFXIV and Chromatics.exe to get back on another game but it "froze" my blackwidow's wave lightning effect. Even though Chromatics.exe was closed. I had to deactivate it from razer synapse to get my blackwidow's lightning back to the normal.

**Comment by logicallysynced** [comment] 2017-03-11 21:01
If you can post the console that will help a lot.

Also have you enabled the Razer devices under the devices tab? Everything is defaultly turned off when you start Chromatics for the first time.

With the persistent lighting, assuming you closed Chromatics properly by rightclicking the icon in the taskbar and selecting close, Razer Synapse has a tendency to do that sometimes and I've found the solution is to replug the device at the USB port. It seems to be a minor Synapse bug, so it's a good idea to make sure there's no Synapse updates that might have got missed.

**Comment by logicallysynced** [comment] 2017-07-03 07:06
Closing due to inactivity.

**Closed as completed by logicallysynced** 2017-07-03 07:06 UTC
Labels: support, Chromatics 2.x
